import { useEffect, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArchiveRestore, CheckCircle, Trash2 } from 'lucide-react';
import { cleanupCandidates, listRemovals, restoreRemoval, scheduleRemoval, type CleanupOutcome, type CleanupView } from '../../services/cleanup';
import type { WorkspaceFile } from '../../services/workspace';
import { formatBytes } from '../../utils';
import { WorkspaceThumbnail } from './MediaTimeline';

const control='min-h-11 rounded-xl border border-telegram-border bg-telegram-surface px-3 text-sm';
export function CleanupPanel({ ownerId, files, onOpen, onFolder }: { ownerId:string;files:WorkspaceFile[];onOpen:(file:WorkspaceFile)=>void;onFolder:(folder:number|null)=>void }) {
    const { t, i18n }=useTranslation(); const queryClient=useQueryClient();
    const [view,setView]=useState<CleanupView>('duplicates');
    const [visibleCount,setVisibleCount]=useState(60);
    const current=useRef({ownerId,view});current.current={ownerId,view};const operation=useRef(0);
    const reviewSection=useRef<HTMLElement>(null);const resultList=useRef<HTMLUListElement>(null);const errorNotice=useRef<HTMLParagraphElement>(null);const reviewTrigger=useRef<HTMLButtonElement|null>(null);
    const [selected,setSelected]=useState<Set<string>>(new Set());
    const [days,setDays]=useState(7); const [review,setReview]=useState(false); const [accepted,setAccepted]=useState(false);
    const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [outcomes,setOutcomes]=useState<(CleanupOutcome & {file?:WorkspaceFile})[]>([]);
    const removals=useQuery({queryKey:['removals',ownerId],queryFn:()=>listRemovals(ownerId),refetchInterval:15_000});
    const pending=new Set(removals.data?.filter(item=>item.status==='pending'||item.status==='deleting').map(item=>item.key)||[]);
    const candidates=useMemo(()=>cleanupCandidates(files,view),[files,view]);
    const selectedFiles=files.filter(file=>selected.has(file.key)&&!pending.has(file.key));
    useEffect(()=>{operation.current++;setSelected(new Set());setReview(false);setAccepted(false);setOutcomes([]);setVisibleCount(60);setBusy(false);setError(null);},[ownerId,view]);
    useEffect(()=>{if(review){reviewSection.current?.scrollIntoView?.({block:'nearest'});reviewSection.current?.focus({preventScroll:true});}},[review]);
    useEffect(()=>{if(outcomes.length){resultList.current?.scrollIntoView?.({block:'nearest'});resultList.current?.focus({preventScroll:true});}},[outcomes]);
    useEffect(()=>{if(error||removals.isError){errorNotice.current?.scrollIntoView?.({block:'nearest'});errorNotice.current?.focus({preventScroll:true});}},[error,removals.isError]);
    const refresh=async()=>{await queryClient.invalidateQueries({queryKey:['removals',ownerId]});await queryClient.invalidateQueries({queryKey:['workspace',ownerId]});};
    const perform=async(action:(isCurrent:()=>boolean)=>Promise<void>)=>{const token=++operation.current;const isCurrent=()=>token===operation.current&&current.current.ownerId===ownerId&&current.current.view===view;setBusy(true);setError(null);try{await action(isCurrent);}catch{if(isCurrent())setError(t('cleanup.error'));}finally{if(isCurrent())setBusy(false);}};
    const schedule=()=>perform(async(isCurrent)=>{const results=await scheduleRemoval(ownerId,selectedFiles.map(file=>file.key),days);if(!isCurrent())return;setOutcomes(results.map(result=>({...result,file:selectedFiles.find(file=>file.key===result.key)})));setSelected(new Set(results.filter(result=>!result.scheduled).map(result=>result.key)));setReview(false);setAccepted(false);await refresh();});
    const date=(value:number)=>new Intl.DateTimeFormat(i18n.language,{dateStyle:'medium',timeStyle:'short'}).format(value);
    return <section className="space-y-5">
        <header><h2 className="text-xl font-semibold">{t('cleanup.title')}</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-telegram-subtext">{t('cleanup.description')}</p></header>
        <div className="flex flex-wrap gap-2" role="group" aria-label={t('cleanup.views')}>{(['duplicates','large','old'] as const).map(value=><button type="button" key={value} aria-pressed={view===value} onClick={()=>setView(value)} className={`${control} ${view===value?'border-telegram-primary text-telegram-primary':''}`}>{t(`cleanup.${value}`)}</button>)}</div>
        {view==='duplicates'&&<p className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-sm">{t('cleanup.possible_only')}</p>}
        {(error||removals.isError)&&<p ref={errorNotice} tabIndex={-1} role="alert" className="rounded-xl border border-red-500/30 p-3 text-sm text-red-400 outline-none">{error||t('cleanup.error')}</p>}
        {candidates.length===0&&<p className="py-6 text-sm text-telegram-subtext">{t('cleanup.no_candidates')}</p>}
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{candidates.slice(0,visibleCount).map(file=><article key={file.key} className={`flex min-w-0 gap-3 rounded-2xl border p-3 ${selected.has(file.key)?'border-telegram-primary bg-telegram-primary/5':'border-telegram-border'}`}>
            <button type="button" onClick={()=>onOpen(file)} aria-label={t('workspace.open_file',{name:file.name})} className="h-20 w-20 shrink-0 overflow-hidden rounded-xl"><WorkspaceThumbnail ownerId={ownerId} file={file}/></button>
            <div className="min-w-0 flex-1"><button type="button" onClick={()=>onOpen(file)} className="block max-w-full truncate text-start text-sm font-medium">{file.name}</button><button type="button" onClick={()=>onFolder(file.folder_id)} className="mt-1 block max-w-full truncate text-start text-xs text-telegram-primary">{file.folderName}</button><p className="mt-1 text-xs text-telegram-subtext">{formatBytes(file.size)}</p><label className="mt-1 flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={selected.has(file.key)} disabled={pending.has(file.key)||busy} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(file.key))next.delete(file.key);else next.add(file.key);return next;})}/>{t(pending.has(file.key)?'cleanup.already_scheduled':'cleanup.select_remove')}</label></div>
        </article>)}</div>
        {visibleCount<candidates.length&&<button type="button" className={control} onClick={()=>setVisibleCount(value=>value+60)}>{t('workspace.show_more')}</button>}
        {selectedFiles.length>0&&<div className="flex flex-wrap items-center gap-3 rounded-xl border border-telegram-border p-3"><p className="flex-1 text-sm">{t('workspace.selected_count',{count:selectedFiles.length})} · {formatBytes(selectedFiles.reduce((total,file)=>total+file.size,0))}</p><button type="button" onClick={event=>{reviewTrigger.current=event.currentTarget;setReview(true);setAccepted(false);}} className={`${control} flex items-center gap-2 text-red-400`}><Trash2 className="h-4 w-4"/>{t('cleanup.review')}</button></div>}
        {review&&<section ref={reviewSection} tabIndex={-1} aria-labelledby="cleanup-review-title" className="space-y-3 rounded-2xl border border-red-500/40 p-4 outline-none"><h3 id="cleanup-review-title" className="font-semibold">{t('cleanup.review')}</h3><ul className="max-h-52 overflow-auto space-y-2 text-sm">{selectedFiles.map(file=><li key={file.key} className="flex justify-between gap-3"><span className="min-w-0 break-words">{file.folderName} / {file.name}</span><span className="shrink-0 text-telegram-subtext">{formatBytes(file.size)}</span></li>)}</ul><label className="flex flex-wrap items-center gap-3 text-sm">{t('cleanup.grace_period')}<select className={control} value={days} onChange={event=>setDays(Number(event.target.value))}>{[1,7,14,30].map(value=><option key={value} value={value}>{t('cleanup.days',{count:value})}</option>)}</select></label><p className="text-sm leading-relaxed text-telegram-subtext">{t('cleanup.retention_explanation')}</p><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)} className="mt-1"/>{t('cleanup.acknowledge')}</label><div className="flex flex-wrap gap-2"><button type="button" disabled={!accepted||busy} onClick={()=>void schedule()} className={`${control} border-red-500/40 text-red-400 disabled:opacity-40`}>{t('cleanup.schedule')}</button><button type="button" onClick={()=>{setReview(false);if(reviewTrigger.current?.isConnected)reviewTrigger.current.focus();}} className={control}>{t('common.cancel')}</button></div></section>}
        {outcomes.length>0&&<ul ref={resultList} tabIndex={-1} aria-label={t('cleanup.outcomes')} className="space-y-3 outline-none">{outcomes.map(result=>{const file=result.file;return <li key={result.key} className="flex items-start gap-2 text-sm"><CheckCircle className={`mt-0.5 h-4 w-4 shrink-0 ${result.scheduled?'text-green-400':'text-red-400'}`}/><div className="min-w-0 flex-1"><p className="break-words">{file?`${file.folderName} / ${file.name}`:result.key}</p><p className="mt-1 text-telegram-subtext">{t(result.scheduled?'cleanup.scheduled':'cleanup.not_scheduled')}</p></div></li>;})}</ul>}
        <section className="space-y-3 border-t border-telegram-border pt-5"><h3 className="text-lg font-semibold">{t('cleanup.recovery_title')}</h3>{!removals.data?.length&&<p className="text-sm text-telegram-subtext">{t('cleanup.recovery_empty')}</p>}{removals.data?.map(removal=><article key={removal.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-telegram-border p-3"><div className="min-w-0 flex-1 basis-60"><p className="break-words text-sm font-medium">{removal.file.name}</p><p className="mt-1 break-words text-xs text-telegram-subtext">{removal.file.folderName} · {t(`cleanup.status.${removal.status}`)}</p>{removal.status==='pending'&&<p className="mt-1 text-xs">{t('cleanup.removal_date',{date:date(removal.deleteAfter)})}</p>}{removal.error&&<p className="text-xs text-amber-400">{t(removal.error==='FILE_CHANGED'?'cleanup.file_changed':'cleanup.waiting_network')}</p>}</div>{['pending','failed'].includes(removal.status)&&<button type="button" disabled={busy} onClick={()=>void perform(async(isCurrent)=>{await restoreRemoval(ownerId,removal.key);if(isCurrent())await refresh();})} className={`${control} flex items-center gap-2 text-telegram-primary`}><ArchiveRestore className="h-4 w-4"/>{t('cleanup.restore')}</button>}</article>)}</section>
    </section>;
}
