#!/usr/bin/env bash
# Injects the custom Android foreground service + manifest permissions into the
# tauri-generated gen/android project (which is regenerated by `tauri android
# init`, so this must run after init and before the gradle build).
set -e
APPDIR="$1"
SRC="$APPDIR/src-tauri/android-native"
GEN="$APPDIR/src-tauri/gen/android"
PKG="$GEN/app/src/main/java/com/cameronamer/telegramdrive"
MANIFEST="$GEN/app/src/main/AndroidManifest.xml"

if [ ! -d "$GEN" ]; then
  echo "inject: gen/android not found at $GEN" >&2
  exit 1
fi

mkdir -p "$PKG"
cp "$SRC/UploadForegroundService.kt" "$PKG/UploadForegroundService.kt"
# Overwrite the generated MainActivity with one that requests POST_NOTIFICATIONS
# (needed on Android 13+ for the upload notification to show).
cp "$SRC/MainActivity.kt" "$PKG/MainActivity.kt"
python3 "$SRC/patch_manifest.py" "$MANIFEST"

# The service's static methods are only ever called from Rust via JNI, so R8
# (release minification) would strip them, breaking start/stop/updateProgress
# with NoSuchMethodError. Keep the class and its members.
PROGUARD="$GEN/app/proguard-rules.pro"
if ! grep -q "UploadForegroundService" "$PROGUARD" 2>/dev/null; then
  cat >> "$PROGUARD" <<'EOF'

-keep class com.cameronamer.telegramdrive.UploadForegroundService { *; }
-keep class com.cameronamer.telegramdrive.UploadForegroundService$* { *; }
EOF
fi
echo "android injection done"
