#!/usr/bin/env bash
# Injects the custom Android foreground service + manifest permissions into the
# tauri-generated gen/android project (which is regenerated by `tauri android
# init`, so this must run after init and before the gradle build).
set -e
APPDIR="$1"
SRC="$APPDIR/src-tauri/android-native"
GEN="$APPDIR/src-tauri/gen/android"
PKG="$GEN/app/src/main/java/com/cameronamer/telegramdrive"
MANIFEST="$GEN/app/src/main/AndroidManifest.xml"

if [ ! -d "$GEN" ]; then
  echo "inject: gen/android not found at $GEN" >&2
  exit 1
fi

mkdir -p "$PKG"
cp "$SRC/UploadForegroundService.kt" "$PKG/UploadForegroundService.kt"
python3 "$SRC/patch_manifest.py" "$MANIFEST"
echo "android injection done"
